#!/bin/bash
# Build LCATS via Python's build module
# Requires:
# - pip install build
echo "Building the lcats package..."
set -x

python -m build

# Turn off logging and print a blank line
{ set +x; } 2>/dev/null
echo
